# Generated by Django 5.2.7 on 2025-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palet_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimization",
            name="container_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Container Yükseklik (cm)"
            ),
        ),
        migrations.AddField(
            model_name="optimization",
            name="container_length",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Container Uzunluk (cm)"
            ),
        ),
        migrations.AddField(
            model_name="optimization",
            name="container_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Container Max Ağırlık (kg)"
            ),
        ),
        migrations.AddField(
            model_name="optimization",
            name="container_width",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Container Genişlik (cm)"
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="custom_boy",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Özel Boy (cm)"
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="custom_en",
            field=models.FloatField(blank=True, null=True, verbose_name="Özel En (cm)"),
        ),
        migrations.AddField(
            model_name="palet",
            name="custom_max_agirlik",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Özel Max Ağırlık (kg)"
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="custom_max_yukseklik",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Özel Max Yükseklik (cm)"
            ),
        ),
        migrations.AlterField(
            model_name="optimization",
            name="palet_tipi",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Avrupa Paleti (120x80x180 cm)"),
                    (2, "ISO Standart (120x100x200 cm)"),
                    (3, "Asya Paleti (110x110x190 cm)"),
                    (4, "ABD Paleti (121.9x101.6x200 cm)"),
                ],
                null=True,
                verbose_name="Palet Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="palet",
            name="palet_tipi",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Avrupa Paleti (120x80x180 cm)"),
                    (2, "ISO Standart (120x100x200 cm)"),
                    (3, "Asya Paleti (110x110x190 cm)"),
                    (4, "ABD Paleti (121.9x101.6x200 cm)"),
                ],
                null=True,
                verbose_name="Palet Tipi",
            ),
        ),
    ]
