# Generated by Django 5.2.7 on 2025-10-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("palet_app", "0002_optimization_container_height_and_more"),
    ]

    operations = []
