# Generated by Django 4.2.7 on 2025-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palet_app", "0003_auto_20251026_2132"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimization",
            name="algoritma",
            field=models.CharField(
                default="greedy", max_length=20, verbose_name="Algoritma"
            ),
        ),
    ]
